# Generated by Django 6.0.3 on 2026-08-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('profile_image', models.ImageField(upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('language', 'Languages'), ('framework', 'Web Frameworks & Libraries'), ('ai_data', 'AI & Data Science'), ('tool', 'Tools')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='Enter GitHub Repository URL', null=True),
        ),
    ]
