# Generated by Django 6.0.3 on 2026-08-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
